#!/bin/bash
shopt -s nullglob

# Path to your tool
TOOL="../../../scripts/json-tool.mjs"

# Loop through all .spdx.json files in the current directory
for file in *.spdx.json; do
    
    # Skip files that were already generated by this script 
    # (prevents processing a -pretty.spdx.json file again)
    if [[ "$file" == *"-pretty.spdx.json" || "$file" == *"-min.spdx.json" || "$file" == *"-canonical.spdx.json" ]]; then
        continue
    fi

    # Extract the base name (everything before the .spdx.json extension)
    base="${file%.spdx.json}"
    echo "Processing $file..."

    node "$TOOL" "$file" pretty > "${base}-pretty.spdx.json" || echo "Failed pretty: $file"
    node "$TOOL" "$file" canon > "${base}-canonical.spdx.json" || echo "Failed canon: $file"
    node "$TOOL" "$file" min > "${base}-min.spdx.json" || echo "Failed min: $file"
done

echo "Done!"

