#!/bin/bash

# Path to your tool
TOOL="../../../scripts/json-tool.js"

# Loop through all .spdx.json files in the current directory
for file in *.spdx.json; do
    
    # Skip files that were already generated by this script 
    # (prevents processing a -pretty.spdx.json file again)
    if [[ "$file" == *"-pretty.spdx.json" || "$file" == *"-min.spdx.json" ]]; then
        continue
    fi

    # Extract the base name (everything before the .spdx.json extension)
    base="${file%.spdx.json}"

    echo "Processing $file..."

    # Run the 'pretty' command
    node "$TOOL" "$file" pretty > "${base}-pretty.spdx.json"

    # Run the 'min' command
    node "$TOOL" "$file" min > "${base}-min.spdx.json"

done

echo "Done!"

