#!/bin/bash
shopt -s nullglob

# Path to your bundled tool
TOOL="json-tool.js"

# Loop through both .spdx.json and .cdx.json files
for file in *.spdx.json *.cdx.json; do
    
    # 1. Skip files that were already generated by this script
    if [[ "$file" == *"-pretty."* || "$file" == *"-min."* || "$file" == *"-canonical."* ]]; then
        continue
    fi

    # 2. Extract the extension (e.g., .spdx.json or .cdx.json)
    # This captures everything from the first dot to the end
    ext="${file#*.}" 
    
    # 3. Extract the base name (everything before the extension)
    base="${file%%.*}"

    echo "Processing $file (Type: $ext)..."

    # Run the commands using the original extension in the new filename
    node "$TOOL" "$file" pretty > "${base}-pretty.${ext}" || echo "Failed pretty: $file"
    node "$TOOL" "$file" canon > "${base}-canonical.${ext}" || echo "Failed canon: $file"
    node "$TOOL" "$file" min > "${base}-min.${ext}" || echo "Failed min: $file"

done

echo "Done!"
